### ISSUE TITLE
Deepin Store does not work when using system proxy

### ISSUE THREAD

**Issue by antoniogermano** [linuxdeepin/deepin-store#48]
I'm using Deepin 15 at work. Everyone needs to use this proxy to work here. The internet simply does not work at all without the proxy.
![deepinscreenshot20160224114144](https://cloud.githubusercontent.com/assets/816290/13288632/9a76641e-daeb-11e5-8ed1-daa181020ada.png)

I have set the proxy settings globally on the system, but Deepin Store does not seem to use them.
![deepinscreenshot20160224113323](https://cloud.githubusercontent.com/assets/816290/13288394/7a630368-daea-11e5-82c0-74c9f109acab.png)

I also needed to override Firefox proxy settings to make Firefox work with the proxy. Simply using system defined proxy didn't work.
![deepinscreenshot20160224113744](https://cloud.githubusercontent.com/assets/816290/13288520/0c6d6834-daeb-11e5-85b8-f4c15b04d92e.png)

Is there a way to fix the system proxy settings or override proxy settings in Deepin Store to make it work? I tried `$ deepin-appstore --help` but it there's no option to override the proxy settings.

Thank you in advance.

_This may be a duplicate of https://github.com/linuxdeepin/deepin-appstore/issues/1
I posted it there at first, but then I realized that the martyr-deepin repo is now the current and official repository (is that correct?), so I posted it here now._

**Comment by antoniogermano** [comment]
Edit: I was mistaken. This is the old repo. I'm closing this issue now as I think people should be using the new repo: https://github.com/linuxdeepin/deepin-appstore

**Comment by Markituss** [comment]
Hi all,
I have the same problem with the store behind proxy in deepin 15.5.
Some help please?
